name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main # ä¿®æ”¹ä¸ºä½ è‡ªå·±çš„é»˜è®¤åˆ†æ”¯å

jobs:
  jekyll-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        

      - name: Setup Ruby âš™ï¸
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # å¯è°ƒæ•´ç‰ˆæœ¬
          bundler-cache: true

      - name: Install dependencies ğŸ”§
        run: |
          gem install bundler
          bundle config set frozen false
          bundle install

      - name: Build the site ğŸ—ï¸
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages 
